package edu.ku.it.si.blackboardcoursesforuser.service;

import java.io.IOException;
import java.rmi.RemoteException;
import java.util.ArrayList;
import java.util.List;

import javax.security.auth.callback.Callback;
import javax.security.auth.callback.CallbackHandler;
import javax.security.auth.callback.UnsupportedCallbackException;

import org.apache.axis2.client.Options;
import org.apache.axis2.client.ServiceClient;
import org.apache.axis2.context.ConfigurationContext;
import org.apache.axis2.context.ConfigurationContextFactory;
import org.apache.axis2.transport.http.HTTPConstants;
import org.apache.log4j.Logger;
import org.apache.rampart.handler.WSSHandlerConstants;
import org.apache.rampart.handler.config.OutflowConfiguration;
import org.apache.ws.security.WSPasswordCallback;
import org.apache.ws.security.handler.WSHandlerConstants;

import edu.emory.mathcs.backport.java.util.Arrays;
import edu.ku.it.si.bbcontextws.generated.ContextWSStub;
import edu.ku.it.si.bbcontextws.generated.ContextWSStub.CourseIdVO;
import edu.ku.it.si.bbcontextws.generated.ContextWSStub.GetMemberships;
import edu.ku.it.si.bbcontextws.generated.ContextWSStub.GetMembershipsResponse;
import edu.ku.it.si.bbcontextws.generated.ContextWSStub.LoginTool;
import edu.ku.it.si.bbcontextws.generated.ContextWSStub.Login;
import edu.ku.it.si.bbcoursews.generated.CourseWSStub;
import edu.ku.it.si.bbcoursews.generated.CourseWSStub.CourseFilter;
import edu.ku.it.si.bbcoursews.generated.CourseWSStub.CourseVO;
import edu.ku.it.si.bbcoursews.generated.CourseWSStub.GetCourse;
import edu.ku.it.si.bbcoursews.generated.CourseWSStub.GetCourseResponse;
import edu.ku.it.si.bbcoursews.generated.ContentWSStub;
import edu.ku.it.si.bbcoursews.generated.ContentWSStub.ContentFilter;
import edu.ku.it.si.bbcoursews.generated.ContentWSStub.ContentVO;
import edu.ku.it.si.bbcoursews.generated.ContentWSStub.GetFilteredContent;
import edu.ku.it.si.bbcoursews.generated.ContentWSStub.GetFilteredContentResponse;
import edu.ku.it.si.bbcoursews.generated.ContentWSStub.GetTOCsByCourseIdResponse;
import edu.ku.it.si.bbcoursews.generated.ContentWSStub.GetTOCsByCourseId;
import edu.ku.it.si.bbcoursews.generated.ContentWSStub.CourseTOCVO;
import edu.ku.it.si.bbcoursews.generated.ContentWSStub.*;


/**
 * Implements methods to enable getting the courses
 * a Blackboard user is enrolled in by using
 * the Blackboard Learn 9.1 web services.
 * 
 * @author bphillips
 *
 */
@SuppressWarnings("deprecation")
public class BlackboardCoursesForUserServiceImpl implements BlackboardCoursesForUserService {

	private static final Logger logger = Logger.getLogger(BlackboardCoursesForUserServiceImpl.class.getName() );

	@Override
	public List<String> getBlackboardCoursesForUser(String modulePath, String blackboardServerURL,
			String sharedSecret, String vendorId, String clientProgramId, String username)
			throws RemoteException {
		
		List<String> courseTitles = new ArrayList<String>();
		
		/*This specifies where the modules directory is located
		In the modules directory must be the rampart.mar file
		which is available from the Rampart download at 
		http://ws.apache.org/rampart/download.html
		*/
		ConfigurationContext ctx = ConfigurationContextFactory.createConfigurationContextFromFileSystem(modulePath);
		
		/*
		 * STEP 1 - Create object of the Web Service we need to use for the operation
		 */

		/*
		 * Create an object of the ContextWSStub.  This class
		 * was generated by using Axis2 and the Context web service
		 * WSDL file.  After generating the file it was copied into 
		 * this project - see package edu.ku.it.si.bbcontextws.generated.
		 * The Context web service is used to get a session id value
		 * from the Blackboard installation and then login using the
		 * the proxy tool.
		 */
		ContextWSStub contextWSStub = new ContextWSStub(ctx,
		"https://" + blackboardServerURL + "/webapps/ws/services/Context.WS");
		
		ServiceClient client = contextWSStub._getServiceClient();

		Options options = client.getOptions();

		options.setProperty(HTTPConstants.HTTP_PROTOCOL_VERSION,
				HTTPConstants.HEADER_PROTOCOL_10);
		
		/*
		 * STEP 2:  Setup the Web Service - Security settings
		 */

		// Next, setup ws-security settings and specify the 
		// CallBackHandler class
		BlackboardCoursesForUserServiceImpl.PasswordCallbackClass pwcb = new BlackboardCoursesForUserServiceImpl.PasswordCallbackClass();

		options.setProperty(WSHandlerConstants.PW_CALLBACK_REF, pwcb);
		
		/*
		 * Must use deprecated class of setting up security because
		 * the SOAP response doesn't include a security header.  Using
		 * the deprecated OutflowConfiguration class we can specify
		 * that the security  header is only for the outgoing SOAP
		 * message.
		 */
		OutflowConfiguration ofc = new OutflowConfiguration();
		ofc.setActionItems("UsernameToken Timestamp");
		ofc.setUser("session");

		ofc.setPasswordType("PasswordText");
		options.setProperty(WSSHandlerConstants.OUTFLOW_SECURITY, ofc.getProperty());
		client.engageModule("rampart");
		
		/*
		 * STEP 3: Get the session ID from Blackboard for using this web service
		 */
		
		// call initialize method of the Context web service to get the sessionid
		String sessionValue = contextWSStub.initialize().get_return();
		
		// set the sessionid on the callback handler so it is used by all subsequent webservice calls.
		pwcb.setSessionId(sessionValue);
		
		/*
		 * STEP 4:  Login to our Blackboard installation using the information for a proxy tool
		 * that is authorized.
		 */
		
		/*Create a LoginTool object that has information
		*needed to authorize this session to use the
		*web services.  In this example, we are using the
        *proxy tool that was previously setup by 
        *another program and approved to access the Blackboard
        *web services classes and methods
		*/
		LoginTool loginArgs = new LoginTool();
	    loginArgs.setPassword( sharedSecret );
	    
	    //see Blackboard administrator proxy tools for vendor id 
	    //and program id values for this tool
	    loginArgs.setClientVendorId( vendorId );
	    loginArgs.setClientProgramId( clientProgramId );
	    loginArgs.setLoginExtraInfo( "" );
	    loginArgs.setExpectedLifeSeconds( 60 * 60 );
		
		//Call the Context Web Services login method 
		//so that the session id is authorized to access
		//web services 
		boolean loginResult = contextWSStub.loginTool(loginArgs).get_return();

		if (loginResult == true) {

			/*
			 * STEP 6 - Use a specific method of the Web Service to perform the operation
			 * we need for this application
			 */
			
			
			/* use the Context web service to get the
			 * Blackboard course memberships for the provided
			 * Blackboard username
			 */
			
			/* Create a GetMemberships object and specify
			 * the username to get the course memberships for
			 * 
			 */
			GetMemberships getMemberships = new GetMemberships();
			getMemberships.setUserid(username);
			
			
			GetMembershipsResponse getMembershipsResponse = contextWSStub.getMemberships(getMemberships);
			
			
			/*
			 * STEP 7 - Process the web service response from our Blackboard installation
			 */
		
			/*
			 * Get the return from calling the web service method
			 * which is an Array of CourseIDVO objects
			 */
			CourseIdVO [] courseIdVOs = getMembershipsResponse.get_return() ;
			
            /*
             *Create an Array of String objects where each String
             *is a Course id value
             */
			
			String [] courseIds = new String[courseIdVOs.length];
			
			int i = 0;
			
			for (CourseIdVO courseIdVO : courseIdVOs) {

				courseIds[i] = courseIdVO.getExternalId() ;
				
				i++;
				
			}
			
			logger.debug("Course ids found for classes " + username + " is enrolled in are " + Arrays.asList(courseIds));
			
			/*
			 * Create a GetCourse object that is used
			 * to specify how we want the Course web
			 * service to filter the Blackboard courses
			 * when we call the Course web service's getCourse
			 * method.
			 */
			GetCourse getCourse = new GetCourse();
			
			CourseFilter courseFilter = new CourseFilter();
			
			//Filter type 3 is for the id value of the 
			//course which is the PK1 column value in 
			//the course_main table
			courseFilter.setFilterType(3);			
			courseFilter.setIds(courseIds);
			getCourse.setFilter(courseFilter);
			
			/*
			 * STEP 8 - Create an object of another Blackboard web service to perform the next operation
			 * we need for this application
			 */
			
			 /*
			 * Use the Course web service classes to get the
			 * Course value object for each course ID 
			 * stored in the courseIds array.
			 */
			CourseWSStub courseWSStub = new CourseWSStub(ctx,
					"https://" + blackboardServerURL + "/webapps/ws/services/Course.WS");

			client = courseWSStub._getServiceClient();

			options = client.getOptions();

			options.setProperty(HTTPConstants.HTTP_PROTOCOL_VERSION,
					HTTPConstants.HEADER_PROTOCOL_10);
			
			/*
			 * STEP 9 - Setup the WS-Security for the request to this web service
			 * NOTE that we will re-use the same callback handler (with its session ID)
			 * as the previous web service request used.
			 */

			// Next, setup ws-security settings
			// Reuse the same callback handler
			options.setProperty(WSHandlerConstants.PW_CALLBACK_REF, pwcb);
			ofc = new OutflowConfiguration();
			ofc.setActionItems("UsernameToken Timestamp");
			ofc.setUser("session");

			ofc.setPasswordType("PasswordText");
			options.setProperty(WSSHandlerConstants.OUTFLOW_SECURITY, ofc
					.getProperty());
			client.engageModule("rampart");
			
			/*
			 * STEP 10 - make the request to this web service
			 */
			
			GetCourseResponse getCourseResponse = courseWSStub.getCourse(getCourse);
			
			
			/*
			 * STEP 11 - process the response from this web service
			 */
			CourseVO [] courseVOs = getCourseResponse.get_return() ;
			
		
			for (CourseVO courseVO : courseVOs) {
				
				courseTitles.add( courseVO.getName() );
				
			}

			GetTOCsByCourseId getTOCsByCourseId = new GetTOCsByCourseId();
			getTOCsByCourseId.setCourseId(courseIds[0]);

			ContentWSStub contentWSStub = new ContentWSStub(ctx,
					"https://" + blackboardServerURL + "/webapps/ws/services/Content.WS");

			client = contentWSStub._getServiceClient();

			options = client.getOptions();

			options.setProperty(HTTPConstants.HTTP_PROTOCOL_VERSION,
					HTTPConstants.HEADER_PROTOCOL_10);
			
			options.setProperty(WSHandlerConstants.PW_CALLBACK_REF, pwcb);
			ofc = new OutflowConfiguration();
			ofc.setActionItems("UsernameToken Timestamp");
			ofc.setUser("session");

			ofc.setPasswordType("PasswordText");
			options.setProperty(WSSHandlerConstants.OUTFLOW_SECURITY, ofc
					.getProperty());
			client.engageModule("rampart");
			
			GetTOCsByCourseIdResponse getTOCsByCourseIdResponse = contentWSStub.getTOCsByCourseId(getTOCsByCourseId);
			
			
			/*
			 * STEP 11 - process the response from this web service
			 */
			CourseTOCVO [] vos = getTOCsByCourseIdResponse.get_return() ;
		
		
			for (CourseTOCVO vo : vos) {
				
				logger.info("Found contentVO : " +vo.getLabel() + " getCourseContentsId " +vo.getCourseContentsId());
				logger.info(" contentVO : " +vo.getId() + " getTocTarget()  " +vo.getTocTarget());
				
			}



					// #########################
			sample.ws.HelloWorldWSStub helloWSStub = new sample.ws.HelloWorldWSStub(ctx,
			"https://" + blackboardServerURL + "/webapps/ws/services/HelloWorld.WS");
			sample.ws.HelloWorldWSStub.Hello hello = new sample.ws.HelloWorldWSStub.Hello();

			client = helloWSStub._getServiceClient();

			options = client.getOptions();

			options.setProperty(HTTPConstants.HTTP_PROTOCOL_VERSION,
					HTTPConstants.HEADER_PROTOCOL_10);
			options.setProperty(WSHandlerConstants.PW_CALLBACK_REF, pwcb);
			ofc = new OutflowConfiguration();
			ofc.setActionItems("UsernameToken Timestamp");
			ofc.setUser("session");

			ofc.setPasswordType("PasswordText");
			options.setProperty(WSSHandlerConstants.OUTFLOW_SECURITY, ofc
					.getProperty());
			client.engageModule("rampart");

			hello.setParam0("Deepak");
			sample.ws.HelloWorldWSStub.HelloResponse helloResponse = helloWSStub.hello(hello);

			logger.debug("Hello ............... " + helloResponse.get_return());

			//###########################
			
			
		}

		
		return courseTitles ;

		
	}
	
	/**
	 * Store the session id value associated with the logged 
	 * in Blackboard web service.
	 * 
	 */
	private static class PasswordCallbackClass implements CallbackHandler {

		String sessionId = null;


		public void setSessionId(String sessionId) {
			this.sessionId = sessionId;
		}


		public void handle(Callback[] callbacks) throws IOException,
				UnsupportedCallbackException {
			for (int i = 0; i < callbacks.length; i++) {
				WSPasswordCallback pwcb = (WSPasswordCallback) callbacks[i];
				String pw = "nosession";

				if (sessionId != null) {
					pw = sessionId;
				}
				pwcb.setPassword(pw);
			}
		}
	}

}
